import test from "node:test";
import assert from "node:assert/strict";
import { ed25519 } from "@noble/curves/ed25519.js";
import { environmentChangeBytes } from "../src/environments.js";
import { environmentChangeHash } from "../src/environment-origin.js";
import { envelopeHash } from "../src/lifecycle-wire.js";
import { trustRootHash, trustRootPayload } from "../src/trust-root.js";
import { recoveryKeys } from "./fixtures.js";
import { nodeHarness,workerHarness,setupEnvironments,freshRecovery,revoke,seeds,b64,sign,type Harness } from "./recovery-origin-fixtures.js";
const legacy="/recovery-vault?capability=issuer-origin-v1",path=legacy+"&envelopeEvidence=recovery-envelope-v1";
async function newRotation(h:Harness){const old=await h.send(legacy,"GET",undefined,"R");assert.equal(old.status,200);const keys=recoveryKeys(Buffer.alloc(32,89),h.account.id,"2"),root={...old.data.trustRoot,recoveryGeneration:"2",recoverySigningPublicKey:keys.signingPublicKey,recoveryReceivingPublicKey:keys.receivingPublicKey};root.signature=sign(trustRootPayload(h.account.id,"1",root),keys.signingSeed);const envelopes=[...old.data.environments].sort((a,b)=>a.environmentId<b.environmentId?-1:1).map((e:{environmentId:string;keyVersion:string},i:number)=>({...e,envelope:b64(Buffer.alloc(80,121+i))}));const proposal={idempotencyKey:"envelope-evidence-new-code",newRecoveryGeneration:"2",newRecoverySigningPublicKey:keys.signingPublicKey,newRecoveryReceivingPublicKey:keys.receivingPublicKey,newTrustRoot:root,envelopes};const challenge=await h.send("/recovery-rotations","POST",proposal,"R");assert.equal(challenge.status,200,JSON.stringify(challenge.data));assert.equal(challenge.data.signingPayload.length,13);const signature=sign(challenge.data.signingPayload,keys.signingSeed),done=await h.send(`/recovery-rotations/${proposal.idempotencyKey}/complete`,"POST",{challengeId:challenge.data.challengeId,signature},"R");assert.equal(done.status,200,JSON.stringify(done.data));return{keys,proposal,challenge:challenge.data,signature,sequence:done.data.sequence};}
for(const [runtime,create] of [["Node TCP",nodeHarness],["workerd HTTP",workerHarness]] as const){
  test(`${runtime} 显式恢复封套证据与原快照同事务，完整签环境变更不混入旧DTO`,async()=>{
    const h=await create();try{await setupEnvironments(h);await revoke(h,"A");await freshRecovery(h);const old=await h.send(legacy,"GET",undefined,"R");assert.equal(old.status,200);assert.equal(Object.hasOwn(old.data,"envelopeEvidence"),false);const full=await h.send(path,"GET",undefined,"R");assert.equal(full.status,200,JSON.stringify(full.data));assert.equal(full.data.sequence,old.data.sequence);assert.deepEqual(full.data.environments,old.data.environments);const evidence=full.data.envelopeEvidence;assert.deepEqual(Object.keys(evidence).sort(),["environmentChanges","profile","recoveryRotations"]);assert.equal(evidence.profile,"harmonia/recovery-envelope-evidence/v1");assert.equal(evidence.environmentChanges.length,2);assert.deepEqual(evidence.recoveryRotations,[]);
      for(const event of evidence.environmentChanges){assert.deepEqual(Object.keys(event).sort(),["authorization","change","origin","sequence"]);assert.deepEqual(Object.keys(event.change).sort(),["change","signature"]);const c=event.change.change;assert.equal(c.keyVersion,full.data.environments.find((e:{environmentId:string})=>e.environmentId===c.environmentId).keyVersion);assert.equal(event.sequence,Number(c.expectedSequence)+1);assert.equal(event.origin.origin.changeHash,environmentChangeHash(environmentChangeBytes(c),event.change.signature));assert.equal(ed25519.verify(Buffer.from(event.change.signature,"base64url"),environmentChangeBytes(c),ed25519.getPublicKey(seeds.B!)),true);assert.equal(c.recoveryEnvelope,full.data.environments.find((e:{environmentId:string})=>e.environmentId===c.environmentId).envelope);}
      for(const query of[path+"&envelopeEvidence=recovery-envelope-v1",legacy+"&envelopeEvidence=unknown",path+"&extra=directory","/recovery-vault?envelopeEvidence=recovery-envelope-v1"]){const invalid=await h.send(query,"GET",undefined,"R");assert.equal(invalid.status,400);assert.deepEqual(Object.keys(invalid.data),["error"]);}
      assert.equal((await h.send(path,"GET",undefined,"login")).status,403);assert.equal((await h.send(path,"GET",undefined,"R","2")).status,401);assert.equal((await h.send(path,"GET",undefined,"R","1","other-account")).status,401);
    }finally{await h.close();}
  });
  test(`${runtime} 当前恢复代际完整原轮换13域与封套清单新码签名可核验，不用HPKE当来源`,async()=>{
    const h=await create();try{await setupEnvironments(h);await freshRecovery(h);const completed=await newRotation(h),response=await h.send(path,"GET",undefined,"R");assert.equal(response.status,200,JSON.stringify(response.data));assert.equal(response.data.recoveryGeneration,"2");assert.equal(response.data.sequence,completed.sequence);const rotations=response.data.envelopeEvidence.recoveryRotations;assert.equal(rotations.length,1);const accepted=rotations[0];assert.deepEqual(Object.keys(accepted).sort(),["proof","proposal","sequence","signature"]);assert.deepEqual(accepted.proposal,completed.proposal);assert.equal(accepted.sequence,completed.sequence);assert.equal(accepted.signature,completed.signature);assert.equal(accepted.proof.envelopesHash,envelopeHash(accepted.proposal.envelopes));assert.equal(accepted.proof.trustRootHash,trustRootHash(h.account.id,"1",completed.proposal.newTrustRoot));assert.equal(accepted.proof.newRecoverySigningPublicKey,completed.keys.signingPublicKey);assert.equal(ed25519.verify(Buffer.from(accepted.signature,"base64url"),new TextEncoder().encode(JSON.stringify(completed.challenge.signingPayload)),Buffer.from(completed.keys.signingPublicKey,"base64url")),true);assert.deepEqual(response.data.environments,completed.proposal.envelopes);assert.equal(response.data.rotationRequired,false);
      const old=await h.send(legacy,"GET",undefined,"R");assert.equal(old.status,200);assert.equal(Object.hasOwn(old.data,"envelopeEvidence"),false);
    }finally{await h.close();}
  });
}
test("Node 攻击替换裸封套不能替换已签承诺，篡改签来源拒且失败SQL读取回滚",async()=>{
  const h=await nodeHarness();try{await setupEnvironments(h);await freshRecovery(h);const original=h.read();h.change(a=>{a.environments["environment-Y"]!.recoveryEnvelope=b64(Buffer.alloc(80,123));});const forged=await h.send(path,"GET",undefined,"R");assert.equal(forged.status,200);const blob=forged.data.environments.find((e:{environmentId:string})=>e.environmentId==="environment-Y").envelope,commitment=forged.data.envelopeEvidence.environmentChanges.find((e:{change:{change:{environmentId:string}}})=>e.change.change.environmentId==="environment-Y").change.change.recoveryEnvelope;assert.notEqual(blob,commitment);assert.equal(commitment,original.environments["environment-Y"]!.recoveryEnvelope);h.change(a=>Object.assign(a,structuredClone(original)));
    h.change(a=>{a.environmentHistory![0]!.change.change.recoveryEnvelope=b64(Buffer.alloc(80,124));});const denied=await h.send(path,"GET",undefined,"R");assert.equal(denied.status,403);assert.deepEqual(Object.keys(denied.data),["error"]);h.change(a=>Object.assign(a,structuredClone(original)));
    await newRotation(h);const complete=h.read();h.change(a=>{Object.values(a.recoveryRotations!)[0]!.signature=b64(Buffer.alloc(64,125));});assert.equal((await h.send(path,"GET",undefined,"R")).data.error,"signature_invalid");h.change(a=>Object.assign(a,structuredClone(complete)));const before=JSON.stringify(h.read()),restore=h.failNextCommit!();try{assert.equal((await h.send(path,"GET",undefined,"R")).status,500);}finally{restore();}assert.equal(JSON.stringify(h.read()),before);assert.equal((await h.send(path,"GET",undefined,"R")).status,200);
  }finally{await h.close();}
});
