import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { build } from "esbuild";
import { Miniflare } from "miniflare";
import { ed25519,x25519 } from "@noble/curves/ed25519.js";
import { fixtureAccount,clientCredential,seeds,recoveryKeys,recoverySeed } from "./fixtures.js";
import { trustRootPayload } from "../src/trust-root.js";
import type { Email } from "../src/email-transport.js";
import type { SyntheticVault,SyntheticRegistry } from "./worker-harness.js";
type RuntimeResponse=Awaited<ReturnType<Miniflare["dispatchFetch"]>>;
const b64=(v:Uint8Array)=>Buffer.from(v).toString("base64url"),sign=(v:unknown,k:Uint8Array)=>b64(ed25519.sign(new TextEncoder().encode(JSON.stringify(v)),k));
const proof=(m:Email)=>JSON.parse(m.text.split("\n").find(v=>v.startsWith("{"))!) as {accountId:string;accountGeneration:string;challengeId:string;token:string};
async function harness(run:(h:{mf:Miniflare;post:(p:string,b:unknown)=>Promise<RuntimeResponse>;info:()=>Promise<any>;vault:(id:string)=>Promise<DurableObjectStub<SyntheticVault>>;registry:()=>Promise<DurableObjectStub<SyntheticRegistry>>;set:(allow:boolean,verify:boolean)=>Promise<void>})=>Promise<void>){
 const dir=mkdtempSync(join(tmpdir(),"harmonia-registration-worker-")),built=await build({entryPoints:["test/worker-harness.ts"],absWorkingDir:process.cwd(),bundle:true,write:false,format:"esm",platform:"browser",target:"es2023",external:["cloudflare:workers","node:*"],define:{Buffer:"Buffer"},banner:{js:'import { Buffer } from "node:buffer";'}});
 const options={modules:true as const,script:built.outputFiles[0]!.text,compatibilityDate:"2026-07-30",compatibilityFlags:["nodejs_compat"],durableObjects:{INSTANCES:{className:"SyntheticRegistry",useSQLite:true},REGISTRATION_FIXTURES:{className:"SyntheticRegistry",useSQLite:true},ACCOUNTS:{className:"SyntheticVault",useSQLite:true},FIXTURES:{className:"SyntheticVault",useSQLite:true}},d1Databases:{DIRECTORY:"directory"},durableObjectsPersist:join(dir,"objects"),d1Persist:join(dir,"directory"),bindings:{ALLOW_REGISTRATION:"false",REQUIRE_EMAIL_VERIFICATION:"true",EMAIL_FROM:"noreply@example.invalid"}};
 const mf=new Miniflare(options),post=(p:string,b:unknown)=>mf.dispatchFetch(`https://selfhost.example.invalid${p}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)});
 try{await run({mf,post,info:async()=>{const r=await mf.dispatchFetch("https://selfhost.example.invalid/instance-info");assert.equal(r.status,200,await r.clone().text());assert.equal(r.headers.get("cache-control"),"no-store");return await r.json();},vault:async id=>(await mf.getDurableObjectNamespace("FIXTURES")).getByName(id) as unknown as DurableObjectStub<SyntheticVault>,registry:async()=>(await mf.getDurableObjectNamespace("REGISTRATION_FIXTURES")).getByName("harmonia-instance-v1") as unknown as DurableObjectStub<SyntheticRegistry>,set:async(allow,verify)=>{await mf.setOptions({...options,bindings:{...options.bindings,ALLOW_REGISTRATION:String(allow),REQUIRE_EMAIL_VERIFICATION:String(verify)}});}});}finally{await mf.dispose();rmSync(dir,{recursive:true,force:true});}
}
const complete=(post:(p:string,b:unknown)=>Promise<RuntimeResponse>,p:ReturnType<typeof proof>)=>post(`/v1/accounts/${p.accountId}/email-verification/complete`,{accountGeneration:p.accountGeneration,challengeId:p.challengeId,token:p.token});
test("真实workerd closed非独占pending/并发首号CAS、冻结verify、终态丢回应login、reset及删空永久关闭",{timeout:180000},async()=>harness(async h=>{
 const i=await h.info();assert.deepEqual(Object.keys(i).sort(),["allowRegistration","emailVerificationRequired","initialRegistrationAvailable","product","protocol","status"]);assert.equal(i.product,"harmonia");assert.deepEqual(i.protocol.supportedMajors,[1]);assert.equal(i.initialRegistrationAvailable,true);
 const accounts=[] as {accountId:string}[];for(const email of ["first@example.invalid","other@example.invalid"]){const r=await h.post("/v1/register",{email,credential:clientCredential});assert.equal(r.status,200,await r.clone().text());accounts.push(await r.json() as {accountId:string});}
 assert.equal((await h.info()).initialRegistrationAvailable,true);await h.set(false,false);assert.equal((await h.info()).emailVerificationRequired,false);
 const proofs=[] as ReturnType<typeof proof>[];for(const a of accounts)proofs.push(proof((await (await h.vault(a.accountId)).mails())[0]!));assert.equal((await h.post("/v1/login",{email:"first@example.invalid",credential:clientCredential})).status,401);
 const finished=await Promise.all(proofs.map(p=>complete(h.post,p)));assert.deepEqual(finished.map(r=>r.status).sort(),[200,403]);const index=finished.findIndex(r=>r.status===200),winner=proofs[index]!,email=index===0?"first@example.invalid":"other@example.invalid";
 assert.equal((await complete(h.post,winner)).status,401);assert.equal((await h.post("/v1/login",{email,credential:"ee".repeat(32)})).status,401);assert.equal((await h.post("/v1/login",{email,credential:clientCredential})).status,200);assert.equal((await h.info()).initialRegistrationAvailable,false);
 assert.equal((await h.post("/v1/account-reset/request",{email:index===0?"other@example.invalid":"first@example.invalid"})).status,403);
 const loserIndex=1-index,loser=proofs[loserIndex]!,loserEmail=index===0?"other@example.invalid":"first@example.invalid";await h.set(true,false);assert.equal((await h.post("/v1/login",{email:loserEmail,credential:"ee".repeat(32)})).status,401);assert.equal((await (await h.vault(loser.accountId)).account(loser.accountId))!.registrationAdmission!.state,"proof-ready");assert.equal((await h.post("/v1/login",{email:loserEmail,credential:clientCredential})).status,200);assert.equal((await (await h.registry()).info()).winnerAccountId,winner.accountId);await h.set(false,false);
 assert.equal((await h.post("/v1/account-reset/request",{email})).status,200);const reset=proof((await (await h.vault(winner.accountId)).mails()).at(-1)!);assert.equal((await h.post(`/v1/accounts/${winner.accountId}/account-reset/complete`,{accountGeneration:"1",challengeId:winner.challengeId,token:winner.token,newCredential:"cd".repeat(32),confirmation:"DELETE_OLD_VAULT"})).status,401);
 const done=await h.post(`/v1/accounts/${winner.accountId}/account-reset/complete`,{accountGeneration:"1",challengeId:reset.challengeId,token:reset.token,newCredential:"cd".repeat(32),confirmation:"DELETE_OLD_VAULT"});assert.equal(done.status,200,await done.clone().text());assert.equal((await (await h.vault(winner.accountId)).account(winner.accountId))!.verificationRequiredAtRegistration,true);
 await h.set(true,false);const optional=await h.post("/v1/register",{email:"optional@example.invalid",credential:clientCredential});assert.equal(optional.status,200);const optionalId=(await optional.json() as {accountId:string}).accountId;assert.equal((await (await h.vault(optionalId)).account(optionalId))!.verified,false);await h.set(false,true);assert.equal((await h.post("/v1/login",{email:"optional@example.invalid",credential:clientCredential})).status,200);
 for(const a of [...accounts,{accountId:optionalId}])await (await h.vault(a.accountId)).removeAccount(a.accountId);await h.set(false,true);assert.equal((await h.info()).initialRegistrationAvailable,false);assert.equal((await h.post("/v1/register",{email:"new@example.invalid",credential:clientCredential})).status,403);
 const db=await h.mf.getD1Database("DIRECTORY");assert.deepEqual((await db.prepare("PRAGMA table_info(account_directory)").all<{name:string}>()).results.map(r=>r.name),["email","account_id"]);
}));
for(const fault of ["decision","activation"] as const)test(`真实workerd ${fault}持久失败/重启原proof补全，wrongcredential不可激活`,{timeout:120000},async()=>harness(async h=>{
 const r=await h.post("/v1/register",{email:"crash@example.invalid",credential:clientCredential});assert.equal(r.status,200);const id=(await r.json() as {accountId:string}).accountId,p=proof((await (await h.vault(id)).mails())[0]!);
 if(fault==="decision")await (await h.registry()).arm();else await (await h.vault(id)).activationFault();const failed=await complete(h.post,p);assert.equal(failed.status,500);assert.equal((await (await h.vault(id)).account(id))!.registrationAdmission!.state,"proof-ready");assert.equal((await h.info()).initialRegistrationAvailable,fault==="decision");
 await h.set(false,false);assert.equal((await h.post("/v1/login",{email:"crash@example.invalid",credential:"ee".repeat(32)})).status,401);assert.equal((await (await h.vault(id)).account(id))!.registrationAdmission!.state,"proof-ready");
 if(fault==="decision")await (await h.registry()).disarm();else await (await h.vault(id)).clearFault();assert.equal((await complete(h.post,p)).status,200);assert.equal((await h.post("/v1/login",{email:"crash@example.invalid",credential:clientCredential})).status,200);
}));
test("真实workerd legacy逐账号adopt与register并发、孤D1不占首号、旧unverified登录配对和boot不锁",{timeout:120000},async()=>harness(async h=>{
 const db=await h.mf.getD1Database("DIRECTORY");await db.prepare("CREATE TABLE IF NOT EXISTS account_directory(email TEXT PRIMARY KEY,account_id TEXT UNIQUE NOT NULL)").run();for(let n=0;n<18;n++)await db.prepare("INSERT INTO account_directory(email,account_id) VALUES(?,?)").bind(`orphan${n}@example.invalid`,`orphan-${String(n).padStart(2,"0")}`).run();
 assert.equal((await h.info()).initialRegistrationAvailable,true);
 // 新独立实例内存/持久库只在注册迁移之前导入旧账号；先前孤目录不会被当作安全状态。
 const a=await fixtureAccount("legacy-actual","legacy@example.invalid");a.verified=false;const recovery=recoveryKeys(recoverySeed,a.id);a.trustRoot={rootDeviceId:"admin",rootSigningPublicKey:a.devices.admin!.signingPublicKey,rootReceivingPublicKey:a.devices.admin!.receivingPublicKey,recoveryGeneration:"1",recoverySigningPublicKey:recovery.signingPublicKey,recoveryReceivingPublicKey:recovery.receivingPublicKey,signature:""};a.trustRoot.signature=sign(trustRootPayload(a.id,a.generation,a.trustRoot),recovery.signingSeed);
 await h.post("/test/seed",a);
 // 测试专用重开迁移标记，模拟升级前旧账号已在D1/DO、没有新instance元数据。
 const registry=await h.registry();await registry.restartLegacyScan();await h.set(false,true);
 const results=await Promise.all([h.info(),h.post("/v1/register",{email:"contender@example.invalid",credential:clientCredential})]);assert.equal(results[0].initialRegistrationAvailable,false);assert.equal((results[1] as RuntimeResponse).status,403);
 const login=await h.post("/v1/login",{email:a.email,credential:clientCredential});assert.equal(login.status,200);const l=await login.json() as {token:string};
 const headers={"content-type":"application/json",authorization:`Bearer ${l.token}`,"x-harmonia-account-generation":"1"};const pair=await h.mf.dispatchFetch(`https://selfhost.example.invalid/v1/accounts/${a.id}/pairings`,{method:"POST",headers,body:JSON.stringify({idempotencyKey:"legacy-pair",deviceId:"legacy-child",signingPublicKey:b64(ed25519.getPublicKey(Buffer.alloc(32,80))),receivingPublicKey:b64(x25519.getPublicKey(Buffer.alloc(32,81))),approverDeviceId:"admin"})});assert.equal(pair.status,200,await pair.clone().text());
 const c=await h.post(`/v1/accounts/${a.id}/boot-challenges`,{deviceId:"admin",accountGeneration:"1"});assert.equal(c.status,200);const challenge=await c.json() as {challengeId:string;signingPayload:string[]};const boot=await h.post(`/v1/accounts/${a.id}/boot-sessions`,{deviceId:"admin",accountGeneration:"1",challengeId:challenge.challengeId,signature:sign(challenge.signingPayload,seeds.admin!)});assert.equal(boot.status,200,await boot.clone().text());
}));
