/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/worker-env.d.ts` (hash: 8e6f434c1a66d258864f46b67074b1d1)
interface __BaseEnv_Env {
	DIRECTORY: D1Database;
	ALLOW_REGISTRATION: string;
	REQUIRE_EMAIL_VERIFICATION: string;
	ACCOUNTS: DurableObjectNamespace<import("./worker").AccountVault>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "AccountVault";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOW_REGISTRATION" | "REQUIRE_EMAIL_VERIFICATION">> {}
}
