/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/worker-env.d.ts` (hash: 4260b8a2c0b53c4b3b35a912676c9f4a)
interface __BaseEnv_Env {
	DIRECTORY: D1Database;
	EMAIL: SendEmail;
	ALLOW_REGISTRATION: string;
	REQUIRE_EMAIL_VERIFICATION: string;
	EMAIL_FROM: string;
	ACCOUNTS: DurableObjectNamespace<import("./worker").AccountVault>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "AccountVault";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOW_REGISTRATION" | "REQUIRE_EMAIL_VERIFICATION" | "EMAIL_FROM">> {}
}
