/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/worker-env.d.ts` (hash: d99e3179f8a0294b6b3e4217c01b29e3)
interface __BaseEnv_Env {
	EMAIL: SendEmail;
	ALLOW_REGISTRATION: string;
	REQUIRE_EMAIL_VERIFICATION: string;
	EMAIL_FROM: string;
	ACCOUNTS: DurableObjectNamespace<import("./worker").AccountVault>;
	INSTANCES: DurableObjectNamespace<import("./worker").InstanceRegistry>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "AccountVault" | "InstanceRegistry";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOW_REGISTRATION" | "REQUIRE_EMAIL_VERIFICATION" | "EMAIL_FROM">> {}
}
